name: action-continuous-translation
description: This action uses GitHub Models and remark to translate markdown
  document incrementally in your repository.
inputs:
  lang:
    description: The ISO code(s) of the target language(s) for translation (comma-separated values).
    required: false
    default: fr,es
  instructions:
    description: Additional prompting instructions that will be injected in the
      translation prompt.
    required: false
  instructions_file:
    description: File containing additional prompting instructions that will be
      injected in the translation prompt.
    required: false
  starlight_dir:
    description: Root directory for the Astro Starlight documentation. Must specify
      starlightBase as well.
    required: false
  starlight_base:
    description: Base path for the Astro Starlight documentation. Used to patch
      links in translations. Must specify starlightDir as well.
    required: false
  force:
    description: Force translation even if the file has already been translated.
    required: false
    default: false
  files:
    description: Files to process, separated by semi columns (;). .md,.mdx
    required: false
  debug:
    description: Enable debug logging
      (https://microsoft.github.io/genaiscript/reference/scripts/logging/).
    required: false
  github_token:
    description: "GitHub token with `models: read` permission at least
      (https://microsoft.github.io/genaiscript/reference/github-actions/#github\
      -models-permissions)., `secrets.GITHUB_TOKEN`"
    required: true
runs:
  using: docker
  image: Dockerfile
