name: action-continuous-translation
description: This action uses GitHub Models and remark to translate markdown
  document incrementally in your repository.
inputs:
  lang:
    description: The iso-code target language for translation.
    required: false
    default: fr
  force:
    description: Force translation even if the file has already been translated.
    required: false
    default: false
  files:
    description: Files to process, separated by semi columns (;). .md,.mdx
    required: false
  debug:
    description: Enable debug logging
      (https://microsoft.github.io/genaiscript/reference/scripts/logging/).
    required: false
  openai_api_key:
    description: OpenAI API key
    required: false
  openai_api_base:
    description: OpenAI API base URL
    required: false
  azure_openai_api_endpoint:
    description: Azure OpenAI endpoint. In the Azure Portal, open your Azure OpenAI
      resource, Keys and Endpoints, copy Endpoint.
    required: false
  azure_openai_api_key:
    description: Azure OpenAI API key. **You do NOT need this if you are using
      Microsoft Entra ID.
    required: false
  azure_openai_subscription_id:
    description: Azure OpenAI subscription ID to list available deployments
      (Microsoft Entra only).
    required: false
  azure_openai_api_version:
    description: Azure OpenAI API version.
    required: false
  azure_openai_api_credentials:
    description: Azure OpenAI API credentials type. Leave as 'default' unless you
      have a special Azure setup.
    required: false
  azure_ai_inference_api_key:
    description: Azure AI Inference key
    required: false
  azure_ai_inference_api_endpoint:
    description: Azure Serverless OpenAI endpoint
    required: false
  azure_ai_inference_api_version:
    description: Azure Serverless OpenAI API version
    required: false
  azure_ai_inference_api_credentials:
    description: Azure Serverless OpenAI API credentials type
    required: false
  github_token:
    description: "GitHub token with `models: read` permission at least
      (https://microsoft.github.io/genaiscript/reference/github-actions/#github\
      -models-permissions)."
    required: false
outputs:
  text:
    description: The generated text output.
runs:
  using: docker
  image: docker://ghcr.io/pelikhan/action-continuous-ai:v0.0.2
