name: action-continuous-translation
description: This action uses GitHub Models and remark to incrementally
  translate markdown documents in your repository.
inputs:
  lang:
    description: The ISO code(s) of the target language(s) for translation
      (comma-separated values).
    required: false
    default: fr
  source:
    description: The ISO code of the source language for translation. Defaults to
      'en' (English).
    required: false
    default: en
  filename_template:
    description: Template (jinja) for the translated file names.
    required: false
    default: "{{dirname}}/{{basename}}.{{lang}}{{extname}}"
  instructions:
    description: Additional prompting instructions that will be injected in the
      translation prompt.
    required: false
  instructions_file:
    description: File containing additional prompting instructions that will be
      injected in the translation prompt.
    required: false
  translations_dir:
    description: Directory where the translations will be stored. Defaults to
      'translations'.
    required: false
    default: translations
  starlight_dir:
    description: Root directory for the Astro Starlight documentation.
    required: false
  starlight_base:
    description: Base path for the Astro Starlight documentation.
    required: false
  glossary_file:
    description: A markdown file containing the glossary of the project
    required: false
  max_translation_tokens:
    description: Maximum number of tokens to process in a translation LLM call.
    required: false
    default: 8000
  max_validation_tokens:
    description: Maximum number of tokens to process in a validation LLM call.
    required: false
    default: 8000
  force:
    description: Force translation even if the file has already been translated.
    required: false
    default: false
  files:
    description: Files to process, separated by semi columns (;). .md,.mdx
    required: false
  debug:
    description: Enable debug logging
      (https://microsoft.github.io/genaiscript/reference/scripts/logging/).
    required: false
  model_alias:
    description: "A YAML-like list of model aliases and model id: `translation:
      github:openai/gpt-4o`"
    required: false
  openai_api_key:
    description: OpenAI API key
    required: false
  openai_api_base:
    description: OpenAI API base URL
    required: false
  azure_openai_api_endpoint:
    description: Azure OpenAI endpoint. In the Azure Portal, open your Azure OpenAI
      resource, Keys and Endpoints, copy Endpoint.
    required: false
  azure_openai_api_key:
    description: Azure OpenAI API key. **You do NOT need this if you are using
      Microsoft Entra ID.
    required: false
  azure_openai_subscription_id:
    description: Azure OpenAI subscription ID to list available deployments
      (Microsoft Entra only).
    required: false
  azure_openai_api_version:
    description: Azure OpenAI API version.
    required: false
  azure_openai_api_credentials:
    description: Azure OpenAI API credentials type. Leave as 'default' unless you
      have a special Azure setup.
    required: false
  azure_ai_inference_api_key:
    description: Azure AI Inference key
    required: false
  azure_ai_inference_api_endpoint:
    description: Azure Serverless OpenAI endpoint
    required: false
  azure_ai_inference_api_version:
    description: Azure Serverless OpenAI API version
    required: false
  azure_ai_inference_api_credentials:
    description: Azure Serverless OpenAI API credentials type
    required: false
  github_token:
    description: "GitHub token with `models: read` permission at least
      (https://microsoft.github.io/genaiscript/reference/github-actions/#github\
      -models-permissions)."
    required: false
runs:
  using: docker
  image: Dockerfile
outputs:
  text:
    description: The generated text output.
branding:
  color: yellow
  icon: globe
