name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    permissions:
      contents: read
      models: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm test
