name: GenAI Issue Deduplication
on:
  issues:
    types: [opened, edited]
permissions:
  issues: write
  contents: read
jobs:
  dedup:
    runs-on: ubuntu-latest
    steps:
      - uses: pelikhan/action-genai-issue-dedup@v0
