name: GenAI Pull Request Descriptor
on:
  pull_request_target: # the code is treated as text, no install/code shall be executed
permissions:
  contents: read
  pull-requests: write
  models: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  genai_pull_request_descriptor:
    runs-on: ubuntu-latest
    steps:
      - uses: pelikhan/action-add-reaction@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction: eyes
      - uses: actions/checkout@v4
      # do not run setup or any code
      - uses: actions/cache@v4
        with:
          path: .genaiscript/cache/**
          key: genaiscript-${{ github.run_id }}
          restore-keys: |
            genaiscript-
      - uses: pelikhan/action-genai-pull-request-descriptor@v0 # update to the major version you want to use
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
