name: GenAI Issue Deduplication
on:
  issues:
    types: [opened, edited]
permissions:
  issues: write
  contents: read
  models: read
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
  add_reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: pelikhan/action-add-reaction@v0
        with:
          reaction: rocket
  label:
    needs: add_reaction
    runs-on: ubuntu-latest
    steps:
      - uses: pelikhan/action-genai-issue-dedup@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
