name: GenAI Issue Labeller
on:
  issues:
    types: [opened, edited]
permissions:
  issues: write
  contents: read
  models: read
concurrency:
    group: ${{ github.workflow }}-${{ github.event.issue.number }}
    cancel-in-progress: true
jobs:
  add_reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: pelikhan/action-add-reaction@v0
        continue-on-error: true
  label:
    needs: add_reaction
    runs-on: ubuntu-latest
    steps:
      - uses: pelikhan/action-genai-issue-labeller@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}