name: GenAI Issue Labeller
on:
  issues:
    types: [opened, edited]
permissions:
  issues: write
  contents: read
  models: read
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: pelikhan/action-add-reaction@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction: eyes
      - uses: pelikhan/action-genai-issue-labeller@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}